/**
 * 🎭 Email Master Template - "Dark Theatre" Design
 * 
 * Dit is het ENIGE template dat gebruikt wordt voor alle email communicatie.
 * De inhoud wordt dynamisch geladen via de ContentBlock parameter.
 * 
 * Kenmerken:
 * - 100% table-based layout (maximum compatibility)
 * - Dark theatre theme (#1a1a1a background, #D4AF37 gold accents)
 * - Web-safe fonts only (Arial, Helvetica, sans-serif)
 * - Bulletproof button design
 * - Responsive width (600px max)
 * 
 * Compatibel met:
 * ✅ Gmail (web + app)
 * ✅ Outlook (2007-2021, 365, web)
 * ✅ Apple Mail
 * ✅ Yahoo Mail
 * ✅ Thunderbird
 * 
 * @author Inspiration Point - November 2025
 */

export interface EmailContentBlock {
  spotlightTitle: string;
  spotlightSubtitle?: string; // Voor urgente berichten (optie vervaldatum)
  greeting: string; // "Beste [Naam],"
  introText?: string; // Optionele intro paragraph
  eventTimesHTML?: string; // Optionele 3-kolommen tijd tabel (generated by formatEventTimesHTML)
  reservationDetails: ReservationDetail[];
  additionalInfo?: string; // Extra informatie blok (HTML toegestaan)
  ctaButton: {
    text: string;
    url: string;
    urgent?: boolean; // Maakt knop meer prominent
  };
  footerNote?: string; // Extra notitie boven de footer
}

export interface ReservationDetail {
  label: string;
  value: string;
  highlight?: boolean; // Maakt value extra prominent (goud)
}

// Kleurenschema - Dark Theatre Theme
const COLORS = {
  // Achtergronden
  bodyBackground: '#1a1a1a',      // Diep donker voor body
  cardBackground: '#2a2a2a',      // Subtiel lichter voor content card
  infoBoxBackground: '#333333',   // Voor info/warning boxes
  
  // Tekst
  textPrimary: '#f1f1f1',         // Hoofdtekst (gebroken wit)
  textSecondary: '#aaaaaa',       // Labels en subtekst
  textMuted: '#888888',           // Footer tekst
  
  // Accenten
  gold: '#D4AF37',                // Primaire accent (goud)
  goldDark: '#B8941F',            // Donkerder goud voor hover states
  
  // Status kleuren
  success: '#4ade80',             // Groen voor bevestigingen
  warning: '#fb923c',             // Oranje voor urgentie
  info: '#60a5fa',                // Blauw voor informatie
} as const;

/**
 * 🎭 MASTER TEMPLATE GENERATOR
 * 
 * Deze functie genereert de volledige HTML email met de opgegeven content.
 */
export const generateEmailHTML = (content: EmailContentBlock, logoUrl?: string): string => {
  const defaultLogoUrl = 'https://inspirationpoint.nl/logo-email.png'; // Placeholder
  const logo = logoUrl || defaultLogoUrl;

  return `
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="format-detection" content="telephone=no" />
  <title>${content.spotlightTitle}</title>
  <!--[if mso]>
  <style type="text/css">
    body, table, td {font-family: Arial, Helvetica, sans-serif !important;}
  </style>
  <![endif]-->
</head>
<body style="margin: 0; padding: 0; background-color: ${COLORS.bodyBackground}; font-family: Arial, Helvetica, sans-serif;">
  
  <!-- 🎭 OUTER CONTAINER TABLE -->
  <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: ${COLORS.bodyBackground};">
    <tr>
      <td align="center" style="padding: 40px 20px;">
        
        <!-- 📦 MAIN CONTAINER (600px max width) -->
        <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="600" style="max-width: 600px; width: 100%;">
          
          <!-- 🎪 1. PODIUM HEADER (Logo) -->
          <tr>
            <td align="center" style="padding: 30px 0;">
              <img src="${logo}" alt="Inspiration Point" width="400" style="display: block; width: 400px; max-width: 100%; height: auto; border: 0;" />
            </td>
          </tr>
          
          <!-- ✨ 2. SPOTLIGHT TITLE -->
          <tr>
            <td align="center" style="padding: 20px 0 30px 0;">
              <h1 style="margin: 0; font-family: Arial, Helvetica, sans-serif; font-size: 28px; font-weight: bold; color: ${COLORS.gold}; line-height: 1.3;">
                ${content.spotlightTitle}
              </h1>
              ${content.spotlightSubtitle ? `
              <p style="margin: 10px 0 0 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-weight: bold; color: ${content.ctaButton.urgent ? COLORS.warning : COLORS.gold};">
                ${content.spotlightSubtitle}
              </p>
              ` : ''}
            </td>
          </tr>
          
          <!-- 🎴 3. WHITE CARD CONTENT BLOCK -->
          <tr>
            <td>
              <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: ${COLORS.cardBackground}; border-radius: 8px;">
                <tr>
                  <td style="padding: 40px;">
                    
                    <!-- GREETING -->
                    <p style="margin: 0 0 20px 0; font-family: Arial, Helvetica, sans-serif; font-size: 16px; color: ${COLORS.textPrimary}; line-height: 1.6;">
                      ${content.greeting}
                    </p>
                    
                    <!-- INTRO TEXT (optional) -->
                    ${content.introText ? `
                    <p style="margin: 0 0 30px 0; font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: ${COLORS.textSecondary}; line-height: 1.6;">
                      ${content.introText}
                    </p>
                    ` : ''}
                    
                    <!-- 📋 RESERVATION DETAILS TABLE (Compacter met kader) -->
                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-bottom: 30px; background-color: #1a1a1a; border: 2px solid ${COLORS.gold}; border-radius: 8px;">
                      <tr>
                        <td style="padding: 25px;">
                          <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                            ${content.reservationDetails.map(detail => `
                            <tr>
                              <td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: ${COLORS.textMuted}; padding: 6px 0; vertical-align: top; width: 40%;">
                                ${detail.label}
                              </td>
                              <td style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: ${detail.highlight ? COLORS.gold : COLORS.textPrimary}; font-weight: ${detail.highlight ? 'bold' : '600'}; padding: 6px 0; vertical-align: top; text-align: right;">
                                ${detail.value}
                              </td>
                            </tr>
                            `).join('')}
                          </table>
                        </td>
                      </tr>
                    </table>
                    
                    <!-- ADDITIONAL INFO BOX (optional) -->
                    ${content.additionalInfo ? `
                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-bottom: 30px; background-color: ${COLORS.infoBoxBackground}; border-radius: 6px;">
                      <tr>
                        <td style="padding: 20px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: ${COLORS.textSecondary}; line-height: 1.6;">
                          ${content.additionalInfo}
                        </td>
                      </tr>
                    </table>
                    ` : ''}
                    
                    <!-- 🎯 BULLETPROOF CTA BUTTON -->
                    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%">
                      <tr>
                        <td align="center" style="padding: 10px 0;">
                          <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                            <tr>
                              <td align="center" style="border-radius: 6px; background-color: ${content.ctaButton.urgent ? COLORS.warning : COLORS.gold};">
                                <a href="${content.ctaButton.url}" target="_blank" style="display: inline-block; padding: 16px 40px; font-family: Arial, Helvetica, sans-serif; font-size: 16px; font-weight: bold; color: ${COLORS.bodyBackground}; text-decoration: none; border-radius: 6px;">
                                  ${content.ctaButton.text}
                                </a>
                              </td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                    </table>
                    
                    ${content.footerNote ? `
                    <!-- FOOTER NOTE -->
                    <p style="margin: 20px 0 0 0; font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: ${COLORS.textSecondary}; line-height: 1.5; text-align: center;">
                      ${content.footerNote}
                    </p>
                    ` : ''}
                    
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          
          <!-- 🎬 FOOTER -->
          <tr>
            <td align="center" style="padding: 30px 20px 40px 20px;">
              <p style="margin: 0 0 10px 0; font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: ${COLORS.textMuted}; line-height: 1.6;">
                <strong>Inspiration Point</strong><br />
                Theaterstraat 123, 1234 AB Amsterdam<br />
                <a href="tel:+31201234567" style="color: ${COLORS.textMuted}; text-decoration: none;">+31 (0)20 123 45 67</a> | 
                <a href="mailto:info@inspirationpoint.nl" style="color: ${COLORS.textMuted}; text-decoration: none;">info@inspirationpoint.nl</a>
              </p>
              <p style="margin: 15px 0 0 0; font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: ${COLORS.textMuted};">
                <a href="https://inspirationpoint.nl/privacy" style="color: ${COLORS.textMuted}; text-decoration: underline;">Privacy Policy</a> | 
                <a href="https://inspirationpoint.nl/unsubscribe" style="color: ${COLORS.textMuted}; text-decoration: underline;">Afmelden</a>
              </p>
            </td>
          </tr>
          
        </table>
        <!-- END MAIN CONTAINER -->
        
      </td>
    </tr>
  </table>
  <!-- END OUTER CONTAINER -->
  
</body>
</html>
  `.trim();
};

/**
 * 🎭 HELPER: Format currency
 */
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('nl-NL', {
    style: 'currency',
    currency: 'EUR',
  }).format(amount);
};

/**
 * 🎭 HELPER: Format date
 */
export const formatDate = (date: Date | string): string => {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('nl-NL', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
};

/**
 * 🎭 HELPER: Format time
 */
export const formatTime = (time: string): string => {
  return time; // Already in HH:MM format
};

/**
 * 🎭 HELPER: Format event tijden op één lijn (compact, gecentreerd) - voor IN het kader
 */
export const formatEventTimesHTML = (doorsOpen: string, startsAt: string, endsAt: string): string => {
  return `
    <div style="text-align: center; padding: 12px; background: #0d0d0d; border-radius: 6px; border-top: 1px solid #2a2a2a; margin-top: 8px;">
      <div style="font-family: Arial, Helvetica, sans-serif; font-size: 15px; color: #f1f1f1; font-weight: 600; letter-spacing: 0.3px;">
        <span style="color: #D4AF37;">⏰</span> ${doorsOpen} <span style="color: #4a4a4a; margin: 0 10px; font-weight: normal;">•</span> ${startsAt} <span style="color: #4a4a4a; margin: 0 10px; font-weight: normal;">•</span> ${endsAt}
      </div>
    </div>
  `;
};
